# Generated by Django 3.1.7 on 2022-10-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carregister_gateentries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateentries',
            old_name='idNumber',
            new_name='numberPlate',
        ),
        migrations.RemoveField(
            model_name='gateentries',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gateentries',
            name='status',
        ),
    ]
