# Generated by Django 3.1.7 on 2022-11-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221030_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='0', max_length=10, null=True)),
            ],
        ),
    ]
