# Generated by Django 3.1.7 on 2022-11-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gatestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpark', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCarPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.IntegerField(default=0)),
            ],
        ),
    ]
