# Generated by Django 3.1.7 on 2022-11-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_carpark_studentcarpark'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregister',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='gateentries',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
